import type { Metadata } from "next";
import { Inter_Tight } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";

const fontSans = Inter_Tight({
  variable: "--font-inter-tight",
  subsets: ["latin"],
});

const fontMono = Inter_Tight({
  variable: "--font-inter-tight-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontSans.variable} ${fontMono.variable} antialiased dark`}
      >
        <SessionProvider>{children}</SessionProvider>
      </body>
    </html>
  );
}
